server:
  port: 8080

jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/aizaowu?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: toor

mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/*.xml
entity_package: xyz.icloudbadguy.aizaowu.entity


